version: '3'

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - .mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_PORT: 3306
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  go:
    build: .
    restart: always
    environment:
      MYSQL_HOST: mysql
      REDIS_HOST: redis
    ports:
      - 8080:8080
    depends_on:
      - mysql
